title: "The Linux Experiment"
description: "Linux Youtuber, now with written articles"
permalink: /:title/
theme-color: "#64baff"
gravatar: 1e319ac4a79a8f5b65329b141cf53d5a

mastodon: thelinuxEXP
twitter: thelinuxEXP

authors:
  nick:
    name: "Nick"
    description: "Youtuber, writer, video maker, and Linux enthusiast"
    gravatar: 264a76e5b40f4bb39787f617b5164b34
  

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
